### ISSUE TITLE
is there a reason DISCO fails to resolve a tree if the tree has more than four species?

### ISSUE THREAD

**Issue by camae2246** [JSdoubleL/DISCO#1]
Hello James, 
I've been using DISCO to resolve a set of multicopy gene trees. I noticed that a big portion of the trees are not resolved because they have less than four species (they don't meet the minimal species criterion). But, I also noticed that a small portion (~1%) of the trees have between four and six species and DISCO failed to produce a resolved tree. Here's an example... 

Tree 81: Tree has 6 species.
Best root had score 792 with 778 duplications; there were 3 ties.
Outgroup: {Me_px_Sstr_Streblomastix_strix}
Decomposition strategy outputted 0 tree(s) with minimum size 4 .

Do you know a reason why this is happening?
Thank you very much!

**Comment by JSdoubleL** [comment]
Hi,

Sorry for the late response. My guess it that, even though there are more then 4 species in the entire tree, there is no set of more then 4 leaves in the tree with the same label that are considered orthologous by DISCO. 

A simple example might be `(((a,b),c),((a,b),d));` this tree would have 4 species; however, `c` and `d` are considered paralogous, since their LCA is a duplication event. In this case, the largest subtree of orthologous leaves would be of size 3. 

I hope this helps! I can also take a look at your input to confirm this is what is happening if you think that would help.

Best, 
James
